mq:
  hostname: 192.168.10.99
  port: 5672
  username: rabbitmq
  password: rabbitmq
  queue: ci-auth-queue
db:
  host: 192.168.10.99
  port: 2424
  username: root
  password: kj3KiwqGHrUWKp8t51MM
log:
  host: 192.168.10.99
  port: 9600

